### ISSUE TITLE
Issue with "DefaultAssets" when building for Windows

### ISSUE THREAD

**Issue by EdvardGrodem** [fsstudio-team/ZeroSimROSUnity#14]
I've been trying to build a single scene to a windows executable for a demo. However, I get a compile error involving a property **DefaultAssets**
`Packages/ZeroSimROSUnity/Runtime/Scripts/Sensors/RGBCamera/ZORGBCamera.cs(132,67): error CS1061: 'ZOROSUnityManager' does not contain a definition for 'DefaultAssets' and no accessible extension method 'DefaultAssets' accepting a first argument of type 'ZOROSUnityManager' could be found (are you missing a using directive or an assembly reference?)
`
I cannot find any reference to **DefaultAssets** on the internet, nor in the ZeroSim code base.
I tried to do a quick fix by commenting out line 127 and 129 to 131. 
https://github.com/fsstudio-team/ZeroSimROSUnity/blob/18ecee0c2ee5993ddf7505bc6168f43b4ed8bf4e/Runtime/Scripts/Sensors/RGBCamera/ZORGBCamera.cs#L127-L131

However, this produces the error
`Error while executing command: Library/PackageCache/com.unity.burst@1.2.3/.Runtime/hostlin/vswhere.exe -legacy -latest -format value  -property installationPath
`
I know ZeroSim is not tested for Windows but I hope someone  have some insight into this issue.

**Comment by micahpearlman** [comment]
@EdvardGrodem turns out that issue in `ZORGBCamera.cs` for creating a standalone executable is also an issue under Linux so we have fixed that and have a new version v0.1.16.  

As far as running under Windows, unfortunately I do not have a Windows workstation to troubleshoot with.  The Burst compiler was being used for LIDAR ray casting -- if you don't need LIDAR you may be able to strip LIDAR out and the Burst compiler dependency.
